# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(408, 308)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 191, 16))
        self.label.setObjectName("label")
        self.heightValue = QtWidgets.QLineEdit(self.centralwidget)
        self.heightValue.setGeometry(QtCore.QRect(230, 30, 151, 21))
        self.heightValue.setObjectName("heightValue")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 191, 16))
        self.label_2.setObjectName("label_2")
        self.weightValue = QtWidgets.QLineEdit(self.centralwidget)
        self.weightValue.setGeometry(QtCore.QRect(230, 70, 151, 21))
        self.weightValue.setObjectName("weightValue")
        self.valueLabel = QtWidgets.QLabel(self.centralwidget)
        self.valueLabel.setGeometry(QtCore.QRect(30, 170, 351, 16))
        self.valueLabel.setObjectName("valueLabel")
        self.suggestion = QtWidgets.QLabel(self.centralwidget)
        self.suggestion.setGeometry(QtCore.QRect(30, 210, 351, 81))
        self.suggestion.setObjectName("suggestion")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 120, 361, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BMI Calculator"))
        self.label.setText(_translate("MainWindow", "Input your height (cm):"))
        self.label_2.setText(_translate("MainWindow", "Input your weight (kg):"))
        self.valueLabel.setText(_translate("MainWindow", "Your BMI: NaN"))
        self.suggestion.setText(_translate("MainWindow", "<html><head/><body><p>No suggestion is available before </p><p>calculation!</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Calculate your BMI NOW!"))
